# Generated by Django 4.2 on 2026-02-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_winner',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Winner'), ('LOST', 'Lost')], default='PENDING', max_length=10),
        ),
    ]
