# Generated by Django 4.2 on 2026-02-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_remove_ticket_is_winner_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='state',
            field=models.CharField(default='Cali', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='zipcode',
            field=models.CharField(default='TXXXXX', max_length=20),
            preserve_default=False,
        ),
    ]
